// <auto-generated />
using System;
using BlazorAppTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorAppTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429065149_Audit")]
    partial class Audit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("test")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorAppTest.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", "test");
                });

            modelBuilder.Entity("BlazorAppTest.Unit.UnitBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("ParentId");

                    b.ToTable("Units", "test");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BlazorAppTest.Unit.DepartmentUnit", b =>
                {
                    b.HasBaseType("BlazorAppTest.Unit.UnitBase");

                    b.ToTable("DepartmentUnits", "test");
                });

            modelBuilder.Entity("BlazorAppTest.Unit.PositionUnit", b =>
                {
                    b.HasBaseType("BlazorAppTest.Unit.UnitBase");

                    b.Property<bool>("IsMultiple")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer");

                    b.ToTable("PositionUnits", "test");
                });

            modelBuilder.Entity("BlazorAppTest.Unit.ProductionUnit", b =>
                {
                    b.HasBaseType("BlazorAppTest.Unit.UnitBase");

                    b.ToTable("ProductionUnits", "test");
                });

            modelBuilder.Entity("BlazorAppTest.Unit.StorageUnit", b =>
                {
                    b.HasBaseType("BlazorAppTest.Unit.UnitBase");

                    b.Property<bool>("IsAutomaticArchiving")
                        .HasColumnType("boolean");

                    b.ToTable("StorageUnits", "test");
                });

            modelBuilder.Entity("BlazorAppTest.Unit.TransportUnit", b =>
                {
                    b.HasBaseType("BlazorAppTest.Unit.UnitBase");

                    b.ToTable("TransportUnits", "test");
                });

            modelBuilder.Entity("BlazorAppTest.Unit.UnitBase", b =>
                {
                    b.HasOne("BlazorAppTest.Unit.UnitBase", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BlazorAppTest.Unit.DepartmentUnit", b =>
                {
                    b.HasOne("BlazorAppTest.Unit.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("BlazorAppTest.Unit.DepartmentUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAppTest.Unit.PositionUnit", b =>
                {
                    b.HasOne("BlazorAppTest.Unit.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("BlazorAppTest.Unit.PositionUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAppTest.Unit.ProductionUnit", b =>
                {
                    b.HasOne("BlazorAppTest.Unit.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("BlazorAppTest.Unit.ProductionUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAppTest.Unit.StorageUnit", b =>
                {
                    b.HasOne("BlazorAppTest.Unit.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("BlazorAppTest.Unit.StorageUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAppTest.Unit.TransportUnit", b =>
                {
                    b.HasOne("BlazorAppTest.Unit.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("BlazorAppTest.Unit.TransportUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAppTest.Unit.UnitBase", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
