// <auto-generated />
using System;
using BlazorAppTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorAppTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("test")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorAppTest.Domain.ReferenceBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReferenceBase", "test");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BlazorAppTest.Unit.UnitBase", b =>
                {
                    b.HasBaseType("BlazorAppTest.Domain.ReferenceBase");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasIndex("ParentId");

                    b.ToTable("Units", "test");
                });

            modelBuilder.Entity("BlazorAppTest.Unit.DepartmentUnit", b =>
                {
                    b.HasBaseType("BlazorAppTest.Unit.UnitBase");

                    b.ToTable("DepartmentUnits", "test");
                });

            modelBuilder.Entity("BlazorAppTest.Unit.PositionUnit", b =>
                {
                    b.HasBaseType("BlazorAppTest.Unit.UnitBase");

                    b.Property<bool>("IsMultiple")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer");

                    b.ToTable("PositionUnits", "test");
                });

            modelBuilder.Entity("BlazorAppTest.Unit.ProductionUnit", b =>
                {
                    b.HasBaseType("BlazorAppTest.Unit.UnitBase");

                    b.ToTable("ProductionUnits", "test");
                });

            modelBuilder.Entity("BlazorAppTest.Unit.StorageUnit", b =>
                {
                    b.HasBaseType("BlazorAppTest.Unit.UnitBase");

                    b.Property<bool>("IsAutomaticArchiving")
                        .HasColumnType("boolean");

                    b.ToTable("StorageUnits", "test");
                });

            modelBuilder.Entity("BlazorAppTest.Unit.TransportUnit", b =>
                {
                    b.HasBaseType("BlazorAppTest.Unit.UnitBase");

                    b.ToTable("TransportUnits", "test");
                });

            modelBuilder.Entity("BlazorAppTest.Unit.UnitBase", b =>
                {
                    b.HasOne("BlazorAppTest.Domain.ReferenceBase", null)
                        .WithOne()
                        .HasForeignKey("BlazorAppTest.Unit.UnitBase", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorAppTest.Unit.UnitBase", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BlazorAppTest.Unit.DepartmentUnit", b =>
                {
                    b.HasOne("BlazorAppTest.Unit.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("BlazorAppTest.Unit.DepartmentUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAppTest.Unit.PositionUnit", b =>
                {
                    b.HasOne("BlazorAppTest.Unit.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("BlazorAppTest.Unit.PositionUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAppTest.Unit.ProductionUnit", b =>
                {
                    b.HasOne("BlazorAppTest.Unit.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("BlazorAppTest.Unit.ProductionUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAppTest.Unit.StorageUnit", b =>
                {
                    b.HasOne("BlazorAppTest.Unit.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("BlazorAppTest.Unit.StorageUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAppTest.Unit.TransportUnit", b =>
                {
                    b.HasOne("BlazorAppTest.Unit.UnitBase", null)
                        .WithOne()
                        .HasForeignKey("BlazorAppTest.Unit.TransportUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAppTest.Unit.UnitBase", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
